{% set name = "streamlit-feedback" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 90f198a4e116e901aaf08058261d444f0abcd3a365bac8c5d6fc08a3c05e02a2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # s390x is missing streamlit
  skip: true  # [py<37 or s390x]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - streamlit >=0.63
  run:
    - python
    - streamlit >=0.63

test:
  imports:
    - streamlit_feedback
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trubrics/streamlit-feedback
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Streamlit component that allows you to collect user feedback in your apps
  description: |
    A Streamlit component to add user feedback to your apps.
  doc_url: https://github.com/trubrics/streamlit-feedback/blob/main/README.md
  dev_url: https://github.com/trubrics/streamlit-feedback

extra:
  recipe-maintainers:
    - psteyer
